MADMAC=$(JAGPATH)/bin/mac
ALN=$(JAGPATH)/bin/aln
CC=m68k-atari-mint-gcc
LIB=$(JAGPATH)/lib/lib
INCL=-I$(JAGPATH)/lib/include
JCP=jcp
VJ=virtualjaguar

ALNFLAGSRAM=-a 4000 x x -rq -v -w -y $(LIB)

ALNFLAGSROM=-a 802000 x 4000 -rq -y $(LIB)

MACFLAGS=-fb -v
CFLAGS=-mc68000 -Wall -fomit-frame-pointer -O2 -msoft-float -funroll-loops $(INCL)
